### ISSUE TITLE
提交一个bug和一些建议

### ISSUE THREAD

**Issue by wby238** [qq573011406/KindleHelper#1]
搜索框的自动完成如果有非文字的部分点击会报错，虽然可以按“继续”来继续使用。

还有就是下载过程中出错的话弹出提示框后按取消就会取消下载，但是偶尔某些源得到的章节有重复的，虽然其中一个获取失败但是另一个是好的。建议更改一下出错后的处理，例如让使用者选择是否继续下载，或者提供一下GET到错误的JSON的log。

尝试过修改出错处理但是不成功……

**Comment by Quanwei1992** [comment]
改好了
