### ISSUE TITLE
失效了 可以更新一下吗。。

### ISSUE THREAD

**Issue by dudt** [qq573011406/KindleHelper#12]
下载下来都是这样的

**Comment by dudt** [comment]
![Snipaste_2019-07-16_22-37-32](https://user-images.githubusercontent.com/19968269/61303586-5b8b9080-a81a-11e9-851c-93fccb725abf.png)

**Comment by Biercenter** [comment]
这是我用过最好的kindle工具了，以前一直用这个下载网络小说，后来176源失效了，再之后也没有添加其它书源，可惜我不会改源码，过来看一下。

**Comment by dudt** [comment]
> 这是我用过最好的点燃工具了，以前一直用这个下载网络小说，后来176源失效了，再之后也没有添加其它书源，可惜我不会改源码，过来看一下。

是啊最好用的。。不知道作者还更不更新这个项目

**Comment by Quanwei1992** [comment]
https://github.com/qq573011406/ebookdownloader
