### ISSUE TITLE
下载不了

### ISSUE THREAD

**Issue by Biercenter** [qq573011406/KindleHelper#2]
不管是优质源还是my716源不行，电子书名《豪门天价前妻：买一送二》
请检查一下，谢谢！

**Comment by Biercenter** [comment]
求更新，真好用

**Comment by Quanwei1992** [comment]
my716加密了

**Comment by Biercenter** [comment]
我抓取了地址，可以打开，就是不知道是什么规律，比如这个地址可以打开。
http://chapter2.zhuishushenqi.com/chapter/http%3A%2F%2Fbook.my716.com%2FgetBooks.aspx%3Fmethod%3Dcontent%26bookId%3D634203%26chapterFile%3DU_719138_201702140026555715_8227_1118.txt

**Comment by Quanwei1992** [comment]
改好了，https://github.com/qq573011406/KindleHelper/releases/tag/v1.2

**Comment by Biercenter** [comment]
非常感谢

**Comment by Quanwei1992** [comment]
不客气

**Comment by Biercenter** [comment]
新版可以下载book.my716的小说了，但是生成mobi的时候没有章节

还有一个小问题，就是上一个版本和这个版本都无法获取小说封面

2017-02-20 18:09 GMT+08:00 袁全伟 <notifications@github.com>:
