### ISSUE TITLE
716源获取不到章节名称

### ISSUE THREAD

**Issue by Biercenter** [qq573011406/KindleHelper#3]
716源基本上章节名都是一个点
如图：
![default](https://cloud.githubusercontent.com/assets/11498308/23330788/4764a2ae-fb92-11e6-989f-7f8baa1b0dd7.PNG)

**Comment by wby238** [comment]
自己改一下就行了啊

**Comment by Biercenter** [comment]
好吧，谢谢😂

2017-02-26 13:13 GMT+08:00 wby238 <notifications@github.com>:
