### ISSUE TITLE
下载部分章节

### ISSUE THREAD

**Issue by cnryb** [qq573011406/KindleHelper#4]
对于那些一直在更新的小说来说或者几千章节的小说，比较需要下载部分章节功能。
需不需要帮你来开发这个功能？

**Comment by Quanwei1992** [comment]
可以啊

**Comment by cnryb** [comment]
好，那等我抽空了就开始搞，当前正在苦逼加班中

**Comment by Biercenter** [comment]
这个功能确实很实用，先谢谢啦！还有期待把book176章节目录显示为 “.” 修复一下，book176是精品源啊。

**Comment by cnryb** [comment]
@Biercenter book176数据看起来是被加密了

**Comment by cnryb** [comment]
@qq573011406 已经发了pr了，有空了处理一下

**Comment by Quanwei1992** [comment]
好

**Comment by Biercenter** [comment]
@cnryb 
小说能下载，就章节下载显示是一个“。”，不过跟追书神器上的章节是一样的，我现在是先把小说从book176上下载，然后再从追书神器上下载章节，用正则表达式替换^\.\r\n每个章节名称，然后用easypub出书。章节可以从http://app.zhuishushenqi.com/atoc/57076a15326011945ee8614a?view=chapters 这样的地址下载处理。

**Comment by Quanwei1992** [comment]
@Biercenter 176源没有章节名字的问题已经解决了.你可以下载最新的代码,编译下就可以了.我还没有来得及上传

**Comment by Biercenter** [comment]
@qq573011406 好的，谢谢！

**Comment by cnryb** [comment]
@Biercenter 我打开你上面写的地址，然后选
